#!/bin/bash
clear
FILE=$1
LINES=$(grep -v "#" $FILE)
HOST=$(hostname -s)
MY_PROMPT="\033[36m$USER\033[m@\033[32m$HOST:\033[33;1m\033[m\$ "
COLOR_PROMPT=$(echo -e "$MY_PROMPT")
IFS=$'\n'
for LINE in $(grep -v "#" $FILE); do
	if [[ $LINE == \$* ]]; then
		#echo -e "$MY_PROMPT $LINE"
		read -p $COLOR_PROMPT
	else
		read 
	fi
done
#echo $LINES
#read -p $COLOR_PROMPT
