#!/bin/bash
IN_PATH="$1"
IN_FILE="$IN_PATH/$(basename $IN_PATH).sh"
BASE=$(basename "$IN_FILE")
BASE=$(basename "$IN_FILE")
OUT_FILE="${BASE%.*}_bash.commands"
CMD="~/k8shelper/scripts/shadow-shell"
echo "!$CMD $IN_FILE" > $OUT_FILE
grep -v '#' $IN_FILE | grep -v '^$' | sed -e 's/$ *//' -e 's/^/!/' >> $OUT_FILE
show-runner applescript -file $OUT_FILE
rm $OUT_FILE
