#!/bin/bash
IN_FILE="$1"
BASE=$(basename "$IN_FILE")
OUT_FILE="${BASE%.*}_bash.commands"
CMD="~/k8shelper/scripts/shadow-shell"
echo "!$CMD $IN_FILE" > $OUT_FILE
grep -v '#' $IN_FILE | grep -v '^$' | sed -e 's/$ *//' -e 's/^/!/' >> $OUT_FILE
show-runner applescript -file $OUT_FILE
rm $OUT_FILE
